- 
  name: Use of conditionals
  hosts: all
  vars:
   - age: 15
  tasks:
    - name: print if name is Ashish
      debug:
        msg: "Hello Ashish"
      when: age > 18
    - name: print if name is Euuropa
      debug:
        msg: "Hello Euuropa"
      when: age <= 18 
     
